language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_TARGET=android-28
  - ANDROID_ABI=armeabi-v7a
android:
  components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
  - tools
  - platform-tools
  # The BuildTools version used by your project
  - build-tools-28.0.3
  # The SDK version used to compile your project
  - android-28


  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

script:
- ./gradlew clean
- ./gradlew module-core:jacocoUnitTestReport -PjacocoBuildType=debug -PjacocoEnv=dev
- ./gradlew module-face-detection:jacocoUnitTestReport -PjacocoBuildType=debug -PjacocoEnv=dev
- ./gradlew module-text-recognition:jacocoUnitTestReport -PjacocoBuildType=debug -PjacocoEnv=dev
- ./gradlew mobile:jacocoUnitTestReport -PjacocoBuildType=debug -PjacocoEnv=dev

#- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#- emulator -avd test -no-skin -no-audio -no-window &
#- android-wait-for-emulator
#- adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
#- ./gradlew connectedCheck

after_success:
- bash <(curl -s https://codecov.io/bash)