# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m

    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum "mobile/build.gradle" }}
    - run:
        name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
        command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum "mobile/build.gradle" }}

    -run:
      name: CleanUp
      command: ./gradlew clean

      - run:
          name: Test module-core
          command: ./gradlew module-core:jacocoTestReport -PjacocoBuildType=debug -PjacocoEnv=dev

      - run:
          name: Test module-face-detection
          command: ./gradlew module-face-detection:jacocoTestReport -PjacocoBuildType=release -PjacocoEnv=dev

      - run:
          name: Test module-text-recognition
          command: ./gradlew module-text-recognition:jacocoTestReport -PjacocoBuildType=release -PjacocoEnv=dev

      - run:
          name: Test mobile
          command: ./gradlew mobile:jacocoTestReport -PjacocoBuildType=release -PjacocoEnv=dev


      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results

