# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m

    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum "mobile/build.gradle" }}
    - run:
        name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
        command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum "mobile/build.gradle" }}

    - run:
        name: CleanUp
        command: ./gradlew clean
    - run:
        name: Test module-core
        command: ./gradlew module-core:jacocoUnitTestReport -PjacocoBuildType=debug -PjacocoEnv=dev
    - run:
        name: Test module-face-detection
        command: ./gradlew module-face-detection:jacocoUnitTestReport -PjacocoBuildType=debug -PjacocoEnv=dev
    - run:
        name: Test module-text-recognition
        command: ./gradlew module-text-recognition:jacocoUnitTestReport -PjacocoBuildType=debug -PjacocoEnv=dev
    - run:
        name: Test mobile
        command: ./gradlew mobile:jacocoUnitTestReport -PjacocoBuildType=debug -PjacocoEnv=dev

    - run:
        name: Trigger codecov publishing
        command: |
          curl https://codecov.io/bash -o codecov.sh
          chmod +x codecov.sh
          ./codecov.sh -X gcov -X coveragepy -X xcode \
              -f module-core/build/reports/jacocoUnitTestReport/jacocoUnitTestReport.xml \
              -f module-face-detection/build/reports/jacocoUnitTestReport/jacocoUnitTestReport.xml \
              -f module-text-recognition/build/reports/jacocoUnitTestReport/jacocoUnitTestReport.xml \
              -f mobile/build/reports/jacocoUnitTestReport/jacocoUnitTestReport.xml

    - store_artifacts:
        path: module-core/build/reports
        destination: reports

    - store_artifacts:
        path: module-face-detection/build/reports
        destination: reports

    - store_artifacts:
        path: module-text-recognition/build/reports
        destination: reports

    - store_artifacts:
        path: mobile/build/reports
        destination: reports

    - store_test_results:
        path: module-core/build/test-results

    - store_test_results:
        path: module-face-detection/build/test-results

    - store_test_results:
        path: module-text-recognition/build/test-results

    - store_test_results:
        path: mobile/build/test-results